before_script:
  - apt-get update -qq
  - apt-get install -qy libelf1
  - npm install --global npm
  - npm install --global lerna@2.0.0-beta.38
  - npm install
test:
  image: 'node:6'
  script:
    - npm test
